//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLServerEntityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }

        private static MyDatabaseEntities myDatabase;

        public static MyDatabaseEntities Instance()
        {
            if (myDatabase == null)
            {
                myDatabase = new MyDatabaseEntities();
            }
            return myDatabase;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Users> Users { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
